Fix po-ops.ts (#111)
* Update po-ops.ts

Not all tools (fex https://github.com/lukaskabrt/PoExtractor) generate a header in the PO/POT file. 
Without this change the tool crashes:

% attranslate --srcFile ./src.pot --targetFile ./en.po --targetLng en --srcLng nb --targetFormat=po --srcFormat=po  
TypeError: Cannot set property 'X-Generator' of undefined
    at Object.parsePotFile (.nvm/versions/node/v10.16.3/lib/node_modules/attranslate/dist/file-formats/po/po-ops.js:62:40)
    at PoFile.readTFile (.nvm/versions/node/v10.16.3/lib/node_modules/attranslate/dist/file-formats/po/po-files.js:15:34)
    at Object.readTFileCore (.nvm/versions/node/v10.16.3/lib/node_modules/attranslate/dist/core/core-util.js:49:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error: Failed to parse './src.pot' with expected format 'po': GetText parsing error

* Linting fix

* CHANGELOG.md

* Test parsing without header

* Revert "Test parsing without header"

This reverts commit df9a25f55bc3f559266f964ad2f6154549a728d7.

* Test without header

* Test fix

* Check

* cancel_others

* Fix YAML error

Co-authored-by: Felix Kirchengast <mail@felixkirchengast.at>